name: Release App

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Lint project
        run: npm run infra:lint
      - name: Build project
        run: npm run infra:build
      - name: Create ZIP Package
        run: |
          mkdir -p dist-package

          cp host.json dist-package/
          cp package.json dist-package/
          cp package-lock.json dist-package/

          cp -r dist dist-package/
          cp -r node_modules dist-package/

          cd dist-package
          zip -r ../app.zip .
          cd ..

          rm -rf dist-package

          mv app.zip dist/
          mv dist/infra/* dist/
          rm -rf dist/src
          rm -rf dist/infra
      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./dist/
          if-no-files-found: error
          overwrite: true
  publish_release:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: package
          path: ./package
          merge-multiple: true
      - name: Create Tag Name
        id: tag_name
        run: echo "tag_name=$(date +'v%Y.%m.%d-%H.%M')" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag_name }}
          release_name: Release ${{ env.tag_name }}
          body: Release of ARM Template on ${{ github.event.repository.updated_at }}
          draft: false
          prerelease: false
      - name: Upload ARM Template
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package/arm-template.json
          asset_name: 'arm-template.json'
          asset_content_type: application/json
      - name: Upload App package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package/app.zip
          asset_name: 'app.zip'
          asset_content_type: application/zip
